# Generated by packamon: do not edit by hand
# Instead of modifying this file, you can modify a template. See ?init for details.

FROM openanalytics/r-ver-tools:4.5.1

# System libraries (incl. system requirements for R packages)
RUN apt-get update && apt-get install --no-install-recommends -y \
    libcairo2-dev \
    libcurl4-openssl-dev \
    libfontconfig1-dev \
    libfreetype6-dev \
    libfribidi-dev \
    libharfbuzz-dev \
    libicu-dev \
    libjpeg-dev \
    libpng-dev \
    libssl-dev \
    libtiff-dev \
    libx11-dev \
    libxml2-dev \
    make \
    pandoc \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install --no-install-recommends -y \
    texinfo \
    texlive-latex-base \
    texlive-latex-recommended \
    texlive-latex-extra \
    # for creation manual (R CMD check)
    texlive-fonts-recommended \
    texlive-fonts-extra \
    # to check size reduction of PDFs
    qpdf \ 
    && rm -rf /var/lib/apt/lists/*
 
RUN echo \
    'options(repos = c(CRAN = gsub("/([0-9-]*)$", "/latest", Sys.getenv("CRAN", "https://cloud.r-project.org")), CRAN.source = "https://cloud.r-project.org"))' \
    >> $(R RHOME)/etc/Rprofile.site

# install dependencies
RUN R -q -e "options(warn = 2); \
    install.packages('remotes'); \
    remotes::install_version('base64enc', version = '0.1-3', upgrade = FALSE); \
    remotes::install_version('bit', version = '4.6.0', upgrade = FALSE); \
    remotes::install_version('brio', version = '1.1.5', upgrade = FALSE); \
    remotes::install_version('cli', version = '3.6.5', upgrade = FALSE); \
    remotes::install_version('clipr', version = '0.8.0', upgrade = FALSE); \
    remotes::install_version('cpp11', version = '0.5.2', upgrade = FALSE); \
    remotes::install_version('crayon', version = '1.5.3', upgrade = FALSE); \
    remotes::install_version('curl', version = '7.0.0', upgrade = FALSE); \
    remotes::install_version('data.table', version = '1.17.8', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('digest', version = '0.6.37', upgrade = FALSE); \
    remotes::install_version('evaluate', version = '1.0.5', upgrade = FALSE); \
    remotes::install_version('farver', version = '2.1.2', upgrade = FALSE); \
    remotes::install_version('fastmap', version = '1.2.0', upgrade = FALSE); \
    remotes::install_version('fontBitstreamVera', version = '0.1.1', upgrade = FALSE); \
    remotes::install_version('fontLiberation', version = '0.1.0', upgrade = FALSE); \
    remotes::install_version('fs', version = '1.6.6', upgrade = FALSE); \
    remotes::install_version('generics', version = '0.1.4', upgrade = FALSE); \
    remotes::install_version('glue', version = '1.8.0', upgrade = FALSE); \
    remotes::install_version('isoband', version = '0.2.7', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('jsonlite', version = '2.0.0', upgrade = FALSE); \
    remotes::install_version('labeling', version = '0.4.3', upgrade = FALSE); \
    remotes::install_version('lattice', version = '0.22-7', upgrade = FALSE); \
    remotes::install_version('lazyeval', version = '0.2.2', upgrade = FALSE); \
    remotes::install_version('magrittr', version = '2.0.3', upgrade = FALSE); \
    remotes::install_version('MASS', version = '7.3-65', upgrade = FALSE); \
    remotes::install_version('mime', version = '0.13', upgrade = FALSE); \
    remotes::install_version('pkgconfig', version = '2.0.3', upgrade = FALSE); \
    remotes::install_version('praise', version = '1.0.0', upgrade = FALSE); \
    remotes::install_version('prettyunits', version = '1.2.0', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('ps', version = '1.9.1', upgrade = FALSE); \
    remotes::install_version('R6', version = '2.6.1', upgrade = FALSE); \
    remotes::install_version('rappdirs', version = '0.3.3', upgrade = FALSE); \
    remotes::install_version('RColorBrewer', version = '1.1-3', upgrade = FALSE); \
    remotes::install_version('Rcpp', version = '1.1.0', upgrade = FALSE); \
    remotes::install_version('rlang', version = '1.1.6', upgrade = FALSE); \
    remotes::install_version('rprojroot', version = '2.1.1', upgrade = FALSE); \
    remotes::install_version('stringi', version = '1.8.7', upgrade = FALSE); \
    remotes::install_version('sys', version = '3.4.3', upgrade = FALSE); \
    remotes::install_version('utf8', version = '1.2.6', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('uuid', version = '1.2-1', upgrade = FALSE); \
    remotes::install_version('viridisLite', version = '0.4.2', upgrade = FALSE); \
    remotes::install_version('withr', version = '3.0.2', upgrade = FALSE); \
    remotes::install_version('xfun', version = '0.53', upgrade = FALSE); \
    remotes::install_version('yaml', version = '2.3.10', upgrade = FALSE); \
    remotes::install_version('zip', version = '2.3.3', upgrade = FALSE); \
    remotes::install_version('askpass', version = '1.2.1', upgrade = FALSE); \
    remotes::install_version('bit64', version = '4.6.0-1', upgrade = FALSE); \
    remotes::install_version('cachem', version = '1.1.0', upgrade = FALSE); \
    remotes::install_version('desc', version = '1.4.3', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('diffobj', version = '0.3.6', upgrade = FALSE); \
    remotes::install_version('fontquiver', version = '0.2.1', upgrade = FALSE); \
    remotes::install_version('highr', version = '0.11', upgrade = FALSE); \
    remotes::install_version('htmltools', version = '0.5.8.1', upgrade = FALSE); \
    remotes::install_version('later', version = '1.4.4', upgrade = FALSE); \
    remotes::install_version('lifecycle', version = '1.0.4', upgrade = FALSE); \
    remotes::install_version('Matrix', version = '1.7-4', upgrade = FALSE); \
    remotes::install_version('nlme', version = '3.1-168', upgrade = FALSE); \
    remotes::install_version('pander', version = '0.6.6', upgrade = FALSE); \
    remotes::install_version('plyr', version = '1.8.9', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('processx', version = '3.8.6', upgrade = FALSE); \
    remotes::install_version('tinytex', version = '0.57', upgrade = FALSE); \
    remotes::install_version('tzdb', version = '0.5.0', upgrade = FALSE); \
    remotes::install_version('xml2', version = '1.4.0', upgrade = FALSE); \
    remotes::install_version('callr', version = '3.7.6', upgrade = FALSE); \
    remotes::install_version('crosstalk', version = '1.2.2', upgrade = FALSE); \
    remotes::install_version('fontawesome', version = '0.5.3', upgrade = FALSE); \
    remotes::install_version('gtable', version = '0.3.6', upgrade = FALSE); \
    remotes::install_version('jquerylib', version = '0.1.4', upgrade = FALSE); \
    remotes::install_version('knitr', version = '1.50', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('memoise', version = '2.0.1', upgrade = FALSE); \
    remotes::install_version('mgcv', version = '1.9-3', upgrade = FALSE); \
    remotes::install_version('openssl', version = '2.3.3', upgrade = FALSE); \
    remotes::install_version('promises', version = '1.3.3', upgrade = FALSE); \
    remotes::install_version('sass', version = '0.4.10', upgrade = FALSE); \
    remotes::install_version('scales', version = '1.4.0', upgrade = FALSE); \
    remotes::install_version('systemfonts', version = '1.2.3', upgrade = FALSE); \
    remotes::install_version('vctrs', version = '0.6.5', upgrade = FALSE); \
    remotes::install_version('waldo', version = '0.6.2', upgrade = FALSE); \
    remotes::install_version('bslib', version = '0.9.0', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('gdtools', version = '0.4.3', upgrade = FALSE); \
    remotes::install_version('hms', version = '1.1.3', upgrade = FALSE); \
    remotes::install_version('httpuv', version = '1.6.16', upgrade = FALSE); \
    remotes::install_version('httr', version = '1.4.7', upgrade = FALSE); \
    remotes::install_version('pillar', version = '1.11.0', upgrade = FALSE); \
    remotes::install_version('pkgbuild', version = '1.4.8', upgrade = FALSE); \
    remotes::install_version('purrr', version = '1.1.0', upgrade = FALSE); \
    remotes::install_version('stringr', version = '1.5.1', upgrade = FALSE); \
    remotes::install_version('textshaping', version = '1.0.3', upgrade = FALSE); \
    remotes::install_version('tidyselect', version = '1.2.1', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('pkgload', version = '1.4.0', upgrade = FALSE); \
    remotes::install_version('progress', version = '1.2.3', upgrade = FALSE); \
    remotes::install_version('ragg', version = '1.5.0', upgrade = FALSE); \
    remotes::install_version('rmarkdown', version = '2.29', upgrade = FALSE); \
    remotes::install_version('tibble', version = '3.3.0', upgrade = FALSE); \
    remotes::install_version('dplyr', version = '1.1.4', upgrade = FALSE); \
    remotes::install_version('forcats', version = '1.0.0', upgrade = FALSE); \
    remotes::install_version('ggplot2', version = '3.5.2', upgrade = FALSE); \
    remotes::install_version('htmlwidgets', version = '1.6.4', upgrade = FALSE); \
    remotes::install_version('officer', version = '0.6.10', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('testthat', version = '3.2.3', upgrade = FALSE); \
    remotes::install_version('vroom', version = '1.6.5', upgrade = FALSE); \
    remotes::install_version('DT', version = '0.33', upgrade = FALSE); \
    remotes::install_version('flextable', version = '0.9.10', upgrade = FALSE); \
    remotes::install_version('readr', version = '2.1.5', upgrade = FALSE); \
    remotes::install_version('tidyr', version = '1.3.1', upgrade = FALSE); \
    remotes::install_version('haven', version = '2.5.5', upgrade = FALSE); \
    remotes::install_version('plotly', version = '4.11.0', upgrade = FALSE); \
    if (!requireNamespace('roxygen2', quietly = TRUE)) install.packages('roxygen2'); \
    if (!requireNamespace('covr', quietly = TRUE)) install.packages('covr')"


